//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppliedResearchAssociates.iAM.Analysis.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppliedResearchAssociates.iAM.Analysis.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;InitialConditionOfNetwork&quot;: 7.037582940694004,
        ///  &quot;InitialSectionSummaries&quot;: [
        ///    {
        ///      &quot;Area&quot;: 224,
        ///      &quot;FacilityName&quot;: &quot;13632&quot;,
        ///      &quot;SectionName&quot;: &quot;21007403200359&quot;,
        ///      &quot;ValuePerNumericAttribute&quot;: {
        ///        &quot;CONDITIONINDEX&quot;: 6.7169999999999996,
        ///        &quot;MINCOND&quot;: 6.7169999999999996,
        ///        &quot;PREV_CULVSEED&quot;: 6,
        ///        &quot;PREV_DECKSEED&quot;: 8,
        ///        &quot;PREV_SUBSEED&quot;: 8,
        ///        &quot;PREV_SUPSEED&quot;: 8,
        ///        &quot;RL_DECKSEEDED&quot;: 0.66999999999999993,
        ///        &quot;RL_SUBSEEDED&quot;: 0.6699999999999999 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Network_13___Simulation_1181_json {
            get {
                return ResourceManager.GetString("Network_13___Simulation_1181_json", resourceCulture);
            }
        }
    }
}
