using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AppliedResearchAssociates.iAM.Reporting.Services.BAMSSummaryReport
{
    public static class BAMSConstants
    {
        public const string AnnualizedAmount = "Annualized Amount";
        public const string BPN1 = "BPN 1";
        public const string BPN2 = "BPN 2";
        public const string BPN3 = "BPN 3";
        public const string BPN4 = "BPN 4";
        public const string BPND = "BPN D";
        public const string BPNH = "BPN H";
        public const string BPNL = "BPN L";
        public const string BPNN = "BPN N";
        public const string BPNT = "BPN T";
        public const string BridgeCare = "Bridge Care";
        public const string BridgeTotal = "Bridge Total";
        public const string Unspecified_Budget = "Unspecified";
        public const string CashNeededByBPN = "Cash Needed By BPN";
        public const string Closed = "Closed";
        public const string ClosedBridgeCountByBPN = "Close BPN Count";
        public const string ClosedBridgeDeckAreaByBPN = "Closed BPN DA";
        public const string CombinedPostedAndClosed = "Combined Posted and Closed";
        public const string CombineNHSNonNHSConditionByBridgeCount = "Combine NHS and Non-NHS Condition By Bridge Count";
        public const string CombineNHSNonNHSConditionByDeckArea = "Combine NHS and Non-NHS Without Committed Projects\nCombine NHS and Non-NHS Without Committed Projects\nCondition By Deck Area";
        public const string CommittedTotal = "Committed Total";
        public const string CulvDurationN = "CULV_DURATION_N";
        public const string Culvert = "culvert";
        public const string CulvertBridgeType = "C";
        public const string CulvertNoTreatment = "C_No Treatment";
        public const string CulvertTotal = "Culvert Total";
        public const string CulvSeeded = "CULV_SEEDED";
        public const string DeckDurationN = "DECK_DURATION_N";
        public const string DeckSeeded = "DECK_SEEDED";
        public const string Fair = "Fair";
        public const string Good = "Good";
        public const string Graph_ClosedBPNCount_Tab = "Close BPN Count";
        public const string Graph_ClosedBPNDA_Tab = "Closed BPN DA";
        public const string Graph_CombinedPostedandClosed_Tab = "Combined Posted and Closed";
        public const string Graph_CombineNHSNonNHSConditionByBridgeCount_Tab = "Combined Count";
        public const string Graph_CombineNHSNonNHSConditionByBridgeCount_Title = "Combine NHS and Non-NHS Condition By Bridge Count";
        public const string Graph_CombineNHSNonNHSConditionByDeckArea_Tab = "Combined DA";
        public const string Graph_CombineNHSNonNHSConditionByDeckArea_Title = "Combine NHS and Non-NHS With Committed Projects\nCondition By Deck Area";
        public const string Graph_DollarNeededDABPN_Tab = "$ Needed DA BPN";
        public const string Graph_NHSConditionByBridgeCount_Tab = "NHS Count";
        public const string Graph_NHSConditionByBridgeCount_Title = "NHS Condition By Bridge Count";
        public const string Graph_NHSConditionByDeckArea_Tab = "NHS DA";
        public const string Graph_NHSConditionByDeckArea_Title = "NHS Condition By DA";
        public const string Graph_NonNHSConditionByBridgeCount_Tab = "Non NHS Count";
        public const string Graph_NonNHSConditionByBridgeCount_Title = "Non-NHS Condition By Bridge Count";
        public const string Graph_NonNHSConditionByDeckArea_Tab = "Non NHS DA";
        public const string Graph_NonNHSConditionByDeckArea_Title = "Non-NHS Condition By Deck Area";
        public const string Graph_PoorCountGraph_Tab = "Poor Count";
        public const string Graph_PoorDAByBPN_Tab = "Poor DA By BPN";
        public const string Graph_PoorDeckAreaGraph_Tab = "Poor DA";
        public const string Graph_PostedBPNCount_Tab = "Posted BPN Count";
        public const string Graph_PostedBPNDA_Tab = "Posted BPN DA";
        public const string NonCulvertBridgeType = "B";
        public const string NonCulvertNoTreatment = "B_No Treatment";
        public const string NoTreatment = "no treatment";
        public const string NoTreatmentForWorkSummary = "No Treatment";
        public const string Overall = "Overall";
        public const string PercentBudgetSpentBAMS = "Percent Budget Spent BAMS";
        public const string PercentBudgetSpentMPMS = "Percent Budget Spent MPMS";
        public const string Poor = "Poor";
        public const string PoorBridgeCompareBridgeCount = "Poor Bridge Compare Bridge Count";
        public const string PoorBridgeCompareDeckArea = "Poor Bridge Compare Deck Area";
        public const string PoorDeckAreaByBPN = "Poor Deck Area By BPN";
        public const string Posted = "Posted";
        public const string PostedBridgeCountByBPN = "Posted Bridge Count By BPN";
        public const string PostedBridgeDeckAreaByBPN = "Posted BPN DA";
        public const string RemainingBudget = "Remaining Budget";
        public const string SubDurationN = "SUB_DURATION_N";
        public const string SubSeeded = "SUB_SEEDED";
        public const string SupDurationN = "SUP_DURATION_N";
        public const string SupSeeded = "SUP_SEEDED";
        public const string Total = "Total";
        public const string TotalBPNCost = "Total BPN Cost";
        public const string TotalBridgeCareBudget = "Total Bridge Care Budget";
        public const string TotalSpent = "Total Spent";
        public const string Work = "Work";
        public const string Yes = "Y";
        public const string No = "N";
    }
}
