<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetFox.Core.Data\AssetFox.Core.Data.csproj" />
    <ProjectReference Include="..\AssetFox.Core.DTOs\AssetFox.Core.DTOs.csproj" />
  </ItemGroup>

</Project>
