//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeCareCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgeCareCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annualized Amount.
        /// </summary>
        internal static string AnnualizedAmount {
            get {
                return ResourceManager.GetString("AnnualizedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 1.
        /// </summary>
        internal static string BPN1 {
            get {
                return ResourceManager.GetString("BPN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 2.
        /// </summary>
        internal static string BPN2 {
            get {
                return ResourceManager.GetString("BPN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 3.
        /// </summary>
        internal static string BPN3 {
            get {
                return ResourceManager.GetString("BPN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN 4.
        /// </summary>
        internal static string BPN4 {
            get {
                return ResourceManager.GetString("BPN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN D.
        /// </summary>
        internal static string BPND {
            get {
                return ResourceManager.GetString("BPND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN H.
        /// </summary>
        internal static string BPNH {
            get {
                return ResourceManager.GetString("BPNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN L.
        /// </summary>
        internal static string BPNL {
            get {
                return ResourceManager.GetString("BPNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN N.
        /// </summary>
        internal static string BPNN {
            get {
                return ResourceManager.GetString("BPNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPN T.
        /// </summary>
        internal static string BPNT {
            get {
                return ResourceManager.GetString("BPNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Care.
        /// </summary>
        internal static string BridgeCare {
            get {
                return ResourceManager.GetString("BridgeCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge Total.
        /// </summary>
        internal static string BridgeTotal {
            get {
                return ResourceManager.GetString("BridgeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Needed By BPN.
        /// </summary>
        internal static string CashNeededByBPN {
            get {
                return ResourceManager.GetString("CashNeededByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close BPN Count.
        /// </summary>
        internal static string ClosedBridgeCountByBPN {
            get {
                return ResourceManager.GetString("ClosedBridgeCountByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed BPN DA.
        /// </summary>
        internal static string ClosedBridgeDeckAreaByBPN {
            get {
                return ResourceManager.GetString("ClosedBridgeDeckAreaByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Posted and Closed.
        /// </summary>
        internal static string CombinedPostedAndClosed {
            get {
                return ResourceManager.GetString("CombinedPostedAndClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine NHS and Non-NHS Condition By Bridge Count.
        /// </summary>
        internal static string CombineNHSNonNHSConditionByBridgeCount {
            get {
                return ResourceManager.GetString("CombineNHSNonNHSConditionByBridgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine NHS and Non-NHS Without Committed Projects
        ///Combine NHS and Non-NHS Without Committed Projects
        ///Condition By Deck Area.
        /// </summary>
        internal static string CombineNHSNonNHSConditionByDeckArea {
            get {
                return ResourceManager.GetString("CombineNHSNonNHSConditionByDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed Total.
        /// </summary>
        internal static string CommittedTotal {
            get {
                return ResourceManager.GetString("CommittedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CULV_DURATION_N.
        /// </summary>
        internal static string CulvDurationN {
            get {
                return ResourceManager.GetString("CulvDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to culvert.
        /// </summary>
        internal static string Culvert {
            get {
                return ResourceManager.GetString("Culvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string CulvertBridgeType {
            get {
                return ResourceManager.GetString("CulvertBridgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_No Treatment.
        /// </summary>
        internal static string CulvertNoTreatment {
            get {
                return ResourceManager.GetString("CulvertNoTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culvert Total.
        /// </summary>
        internal static string CulvertTotal {
            get {
                return ResourceManager.GetString("CulvertTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CULV_SEEDED.
        /// </summary>
        internal static string CulvSeeded {
            get {
                return ResourceManager.GetString("CulvSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECK_DURATION_N.
        /// </summary>
        internal static string DeckDurationN {
            get {
                return ResourceManager.GetString("DeckDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECK_SEEDED.
        /// </summary>
        internal static string DeckSeeded {
            get {
                return ResourceManager.GetString("DeckSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        internal static string Fair {
            get {
                return ResourceManager.GetString("Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close BPN Count.
        /// </summary>
        internal static string Graph_ClosedBPNCount_Tab {
            get {
                return ResourceManager.GetString("Graph_ClosedBPNCount_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed BPN DA.
        /// </summary>
        internal static string Graph_ClosedBPNDA_Tab {
            get {
                return ResourceManager.GetString("Graph_ClosedBPNDA_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Posted and Closed.
        /// </summary>
        internal static string Graph_CombinedPostedandClosed_Tab {
            get {
                return ResourceManager.GetString("Graph_CombinedPostedandClosed_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Count.
        /// </summary>
        internal static string Graph_CombineNHSNonNHSConditionByBridgeCount_Tab {
            get {
                return ResourceManager.GetString("Graph_CombineNHSNonNHSConditionByBridgeCount_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine NHS and Non-NHS Condition By Bridge Count.
        /// </summary>
        internal static string Graph_CombineNHSNonNHSConditionByBridgeCount_Title {
            get {
                return ResourceManager.GetString("Graph_CombineNHSNonNHSConditionByBridgeCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined DA.
        /// </summary>
        internal static string Graph_CombineNHSNonNHSConditionByDeckArea_Tab {
            get {
                return ResourceManager.GetString("Graph_CombineNHSNonNHSConditionByDeckArea_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine NHS and Non-NHS With Committed Projects
        ///Condition By Deck Area.
        /// </summary>
        internal static string Graph_CombineNHSNonNHSConditionByDeckArea_Title {
            get {
                return ResourceManager.GetString("Graph_CombineNHSNonNHSConditionByDeckArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ Needed DA BPN.
        /// </summary>
        internal static string Graph_DollarNeededDABPN_Tab {
            get {
                return ResourceManager.GetString("Graph_DollarNeededDABPN_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Count.
        /// </summary>
        internal static string Graph_NHSConditionByBridgeCount_Tab {
            get {
                return ResourceManager.GetString("Graph_NHSConditionByBridgeCount_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Condition By Bridge Count.
        /// </summary>
        internal static string Graph_NHSConditionByBridgeCount_Title {
            get {
                return ResourceManager.GetString("Graph_NHSConditionByBridgeCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS DA.
        /// </summary>
        internal static string Graph_NHSConditionByDeckArea_Tab {
            get {
                return ResourceManager.GetString("Graph_NHSConditionByDeckArea_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Condition By DA.
        /// </summary>
        internal static string Graph_NHSConditionByDeckArea_Title {
            get {
                return ResourceManager.GetString("Graph_NHSConditionByDeckArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non NHS Count.
        /// </summary>
        internal static string Graph_NonNHSConditionByBridgeCount_Tab {
            get {
                return ResourceManager.GetString("Graph_NonNHSConditionByBridgeCount_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-NHS Condition By Bridge Count.
        /// </summary>
        internal static string Graph_NonNHSConditionByBridgeCount_Title {
            get {
                return ResourceManager.GetString("Graph_NonNHSConditionByBridgeCount_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non NHS DA.
        /// </summary>
        internal static string Graph_NonNHSConditionByDeckArea_Tab {
            get {
                return ResourceManager.GetString("Graph_NonNHSConditionByDeckArea_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-NHS Condition By Deck Area.
        /// </summary>
        internal static string Graph_NonNHSConditionByDeckArea_Title {
            get {
                return ResourceManager.GetString("Graph_NonNHSConditionByDeckArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Count.
        /// </summary>
        internal static string Graph_PoorCountGraph_Tab {
            get {
                return ResourceManager.GetString("Graph_PoorCountGraph_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor DA By BPN.
        /// </summary>
        internal static string Graph_PoorDAByBPN_Tab {
            get {
                return ResourceManager.GetString("Graph_PoorDAByBPN_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor DA.
        /// </summary>
        internal static string Graph_PoorDeckAreaGraph_Tab {
            get {
                return ResourceManager.GetString("Graph_PoorDeckAreaGraph_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted BPN Count.
        /// </summary>
        internal static string Graph_PostedBPNCount_Tab {
            get {
                return ResourceManager.GetString("Graph_PostedBPNCount_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted BPN DA.
        /// </summary>
        internal static string Graph_PostedBPNDA_Tab {
            get {
                return ResourceManager.GetString("Graph_PostedBPNDA_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string NonCulvertBridgeType {
            get {
                return ResourceManager.GetString("NonCulvertBridgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_No Treatment.
        /// </summary>
        internal static string NonCulvertNoTreatment {
            get {
                return ResourceManager.GetString("NonCulvertNoTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no treatment.
        /// </summary>
        internal static string NoTreatment {
            get {
                return ResourceManager.GetString("NoTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Treatment.
        /// </summary>
        internal static string NoTreatmentForWorkSummary {
            get {
                return ResourceManager.GetString("NoTreatmentForWorkSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        internal static string Overall {
            get {
                return ResourceManager.GetString("Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Budget Spent BAMS.
        /// </summary>
        internal static string PercentBudgetSpentBAMS {
            get {
                return ResourceManager.GetString("PercentBudgetSpentBAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Budget Spent MPMS.
        /// </summary>
        internal static string PercentBudgetSpentMPMS {
            get {
                return ResourceManager.GetString("PercentBudgetSpentMPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        internal static string Poor {
            get {
                return ResourceManager.GetString("Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Bridge Compare Bridge Count.
        /// </summary>
        internal static string PoorBridgeCompareBridgeCount {
            get {
                return ResourceManager.GetString("PoorBridgeCompareBridgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Bridge Compare Deck Area.
        /// </summary>
        internal static string PoorBridgeCompareDeckArea {
            get {
                return ResourceManager.GetString("PoorBridgeCompareDeckArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor Deck Area By BPN.
        /// </summary>
        internal static string PoorDeckAreaByBPN {
            get {
                return ResourceManager.GetString("PoorDeckAreaByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        internal static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted Bridge Count By BPN.
        /// </summary>
        internal static string PostedBridgeCountByBPN {
            get {
                return ResourceManager.GetString("PostedBridgeCountByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted BPN DA.
        /// </summary>
        internal static string PostedBridgeDeckAreaByBPN {
            get {
                return ResourceManager.GetString("PostedBridgeDeckAreaByBPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Budget.
        /// </summary>
        internal static string RemainingBudget {
            get {
                return ResourceManager.GetString("RemainingBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB_DURATION_N.
        /// </summary>
        internal static string SubDurationN {
            get {
                return ResourceManager.GetString("SubDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUB_SEEDED.
        /// </summary>
        internal static string SubSeeded {
            get {
                return ResourceManager.GetString("SubSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUP_DURATION_N.
        /// </summary>
        internal static string SupDurationN {
            get {
                return ResourceManager.GetString("SupDurationN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUP_SEEDED.
        /// </summary>
        internal static string SupSeeded {
            get {
                return ResourceManager.GetString("SupSeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total BPN Cost.
        /// </summary>
        internal static string TotalBPNCost {
            get {
                return ResourceManager.GetString("TotalBPNCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bridge Care Budget.
        /// </summary>
        internal static string TotalBridgeCareBudget {
            get {
                return ResourceManager.GetString("TotalBridgeCareBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Spent.
        /// </summary>
        internal static string TotalSpent {
            get {
                return ResourceManager.GetString("TotalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
