<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AssemblyName>AssetFox.Core.DataPersistenceCore</AssemblyName>
    <RootNamespace>AssetFox.Core.DataPersistenceCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetFox.Core.Aggregation\AssetFox.Core.Aggregation.csproj" />
    <ProjectReference Include="..\AssetFox.Core.DataMiner\AssetFox.Core.DataMiner.csproj" />
    <ProjectReference Include="..\AssetFox.Core.Segmentation\AssetFox.Core.Segmentation.csproj" />
  </ItemGroup>

</Project>
