<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Configurations>Debug;Release;MsSqlDebug;Test</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='MsSqlDebug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="2.8.26" />
    <PackageReference Include="MathNet.Numerics" Version="4.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssetFox.CalculateEvaluate\AssetFox.CalculateEvaluate.csproj" />
    <ProjectReference Include="..\AssetFox.Choice\AssetFox.Choice.csproj" />
    <ProjectReference Include="..\AssetFox.CycleDetection\AssetFox.CycleDetection.csproj" />
    <ProjectReference Include="..\AssetFox.Core.Analysis.Logic\AssetFox.Core.Analysis.Logic.csproj" />
    <ProjectReference Include="..\AssetFox.Core.Data\AssetFox.Core.Data.csproj" />
    <ProjectReference Include="..\AssetFox.Core.DTOs\AssetFox.Core.DTOs.csproj" />
    <ProjectReference Include="..\AssetFox.Option\AssetFox.Option.csproj" />
    <ProjectReference Include="..\AssetFox.Validation\AssetFox.Validation.csproj" />
    <ProjectReference Include="..\AssetFox.Zip\AssetFox.Zip.csproj" />
  </ItemGroup>

</Project>
